### ISSUE TITLE
Version Covers the Project Name

### ISSUE THREAD

**Issue by rwinch** [micrometer-metrics/antora-ui-micrometer#3]
Looking at https://docs.micrometer.io/context-propagation/reference/ the version covers the project name in Chrome on Linux

![image](https://github.com/micrometer-metrics/antora-ui-micrometer/assets/362503/e7a03a34-444c-44f9-8426-7414f1c643ce)

**Comment by shakuzen** [comment]
I believe this may be resolved now where it will shorten the name and add ellipsis. Can you confirm it looks the same for you? Maybe we want to drop "Micrometer" from the front of the name to avoid it being shortened now.
![image](https://github.com/micrometer-metrics/antora-ui-micrometer/assets/8924140/49ca35e1-3c85-4b0f-9e86-86ef3467f6f6)

**Comment by oodamien** [comment]
Fix with the last rebase
